---

# PHP Configuration
php_versions:
    - "8.1"
    - "8.2"
    - "8.3"

php_default_version: "php8.3"

php_extensions:
    - cli
    - fpm
    - mysql
    - curl
    - mbstring
    - xml
    - zip
    - bcmath
    - tokenizer
    - gd
    - intl
    - redis
    - opcache
    - imagick

# MariaDB Configuration
mariadb_version: "11.8"
mariadb_key_url: "https://mariadb.org/mariadb_release_signing_key.pgp"
mariadb_key_path: "/etc/apt/keyrings/mariadb-keyring.pgp"

# Postgresql Configuration
pg_version: "18"
pg_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
pg_key_path: "/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc"

# Redis Configuration
redis_gpg_url: "https://packages.redis.io/gpg"
redis_keyring_path: "/usr/share/keyrings/redis-archive-keyring.gpg"
distro_codename_redis: "{{ ansible_distribution_release }}" # Mengambil codename distribusi secara otomatis (cth: jammy, noble, bookworm)

# Supabase Configuration
# base_dir: "/opt/supabase" # custom dengan dir project
repo_dir: "/opt/supabase/"
project_dir: "/opt/supabase/supabase-project"
supabase_repo: "https://github.com/supabase/supabase"

# NodeJS Configuration
nodejs_version: "24"
nvm_version: "v0.40.1"
nvm_dir: "{{ ansible_facts['env']['HOME'] }}/.nvm"

# RabbitMQ
rabbitmq_version: "latest"
distro_codename_rabbitmq: "noble"
keyring_path: "/usr/share/keyrings/com.rabbitmq.team.gpg"
erlang_packages:
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl

# Docker Configuration
docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_path: "/etc/apt/keyrings/docker.asc"
docker_repo_url: "https://download.docker.com/linux/ubuntu"

docker_packages:
  - ca-certificates
  - curl
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Kubernetes(Microk8s) Configuration
target_user: "staging"
kubectl_version: "https://dl.k8s.io/release/stable.txt" #versi stable

# System timezone
timezone: "Asia/Jakarta"

# Swapfile size
swap_size_mb: 2