---

# INSTALL SUPABASE VIA DOCKER COMPOSE

# Clone repository Supabase
- name: Clone Supabase dengan Sparse Checkout
  shell: |
    cd /opt/
    git clone --filter=blob:none --no-checkout {{ supabase_repo }}
    cd supabase
    git sparse-checkout set --cone docker && git checkout master
  args:
    executable: /bin/bash
    creates: "{{ repo_dir }}/.git"  # Skip jika sudah pernah clone

- name: Buat direktori supabase-project
  file:
    path: "{{ project_dir }}"
    state: directory

# Copy folder
- name: Copy file Docker Compose ke direktori project
  copy:
    src: "{{ repo_dir }}/docker/"
    dest: "{{ project_dir }}/"
    remote_src: yes
    mode: 'preserve'

# Copy .env
- name: Copy file .env dari example
  copy:
    src: "{{ project_dir }}/.env.example"
    dest: "{{ project_dir }}/.env"
    remote_src: yes
    force: no # Agar data tidak ditimpa jika sudah ada

# Pull image 
- name: Pull Docker images terbaru
  command: docker compose pull
  args:
    chdir: "{{ project_dir }}"

# Running Supabase with Docker compose
- name: Jalankan Supabase Stack
  command:
    cmd: docker compose up -d
    chdir: "{{ project_dir }}"
  register: compose_up
  changed_when: "'Started' in compose_up.out"

# Check status
- name: Status Verifikasi
  debug:
    msg: "Supabase berjalan di {{ project_dir }}. Cek status dengan 'docker ps'"