---
  
- name: Install Curl Dependensi
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Cek apakah NVM sudah terinstall
  stat:
    path: "{{ nvm_dir }}/nvm.sh"
  register: nvm_stat

- name: Download dan install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  when: not nvm_stat.stat.exists

- name: Download dan install Node.js versi {{ nodejs_version }} via NVM
  shell: >
    source {{ nvm_dir }}/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}
  args:
    executable: /bin/bash
    creates: "{{ nvm_dir }}/versions/node/v{{ nodejs_version }}*"

- name: Verifikasi instalasi Node.js
  shell: >
    source {{ nvm_dir }}/nvm.sh && node -v
  args:
    executable: /bin/bash
  register: node_v_output

- name: Tampilkan versi Node.js
  debug:
    msg: "Node.js terinstal dengan versi: {{ node_v_output.stdout }}"

- name: Verifikasi instalasi NPM
  shell: >
    source {{ nvm_dir }}/nvm.sh && npm -v
  args:
    executable: /bin/bash
  register: npm_v_output

- name: Tampilkan versi NPM
  debug:
    msg: "NPM terinstal dengan versi: {{ npm_v_output.stdout }}"