---

#Create dependency
- name: Install dependensi dasar
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl

- name: Pastikan direktori keyrings ada
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_gpg_url }}"
    dest: "{{ docker_gpg_path }}"
    mode: '0644'

- name: Tambahkan Docker Repository
  copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: {{ docker_repo_url }}
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: stable
      Architectures: {{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}
      Signed-By: {{ docker_gpg_path }}
    mode: '0644'

- name: Update cache dan install Docker engine
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Pastikan Docker service berjalan dan enable on boot
  service:
    name: docker
    state: started
    enabled: yes

# Create docker volume for Portainer
# - name: Buat volume untuk data Portainer
#   docker_volume:
#     name: portainer_data
#     state: present

# # Check if portainer available
# - name: Cek apakah container portainer sudah ada
#   shell: docker ps -a --format '{{"{{.Names}}"}}' | grep -w portainer
#   register: portainer_check
#   ignore_errors: true

# # Create Portainer CE
# - name: Jalankan Portainer CE Container
#   community.docker.docker_container:
#     name: portainer
#     image: portainer/portainer-ce:latest
#     state: started
#     restart_policy: always
#     ports:
#       - "8000:8000"
#       - "9443:9443"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - portainer_data:/data

# # Verification Portainer service
# - name: Verifikasi status Portainer
#   command: docker ps -f name=portainer
#   register: portainer_status
#   changed_when: false

# Check docker installation
- name: Selesai
  debug:
    msg: "Docker terinstal. Akses Portainer di port 9443"